-- MySQL Script generated by MySQL Workbench
-- Thu Apr 12 23:24:05 2016
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ofPositions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ofPositions` (
  `postionID` BIGINT NOT NULL AUTO_INCREMENT,
  `Id` VARCHAR(100) NOT NULL,
  `Lat` VARCHAR(64) NOT NULL,
  `Lng` VARCHAR (64) NOT NULL,
  `creationDate` CHAR(15) NOT NULL,

  PRIMARY KEY (`postionID`))
ENGINE = InnoDB;


INSERT INTO ofVersion (name, version) VALUES ('openfire', 10);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
